# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\jiejieTop\pyqt5\wit\wit.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 753)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 141, 333))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit.setText("")
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_2.setText("")
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_3.setText("")
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.Label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_8.setObjectName("Label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_4)
        self.Label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_9.setObjectName("Label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.LineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_5)
        self.Label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_10.setObjectName("Label_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.LineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_6)
        self.Label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_11.setObjectName("Label_11")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.LineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_7)
        self.Label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_12.setObjectName("Label_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.LineEdit_8 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_8)
        self.lEDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.lEDLabel.setObjectName("lEDLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel)
        self.LineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_9.setObjectName("LineEdit_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_9)
        self.bEEPLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.bEEPLabel.setObjectName("bEEPLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel)
        self.LineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_10.setObjectName("LineEdit_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_10)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 310, 61, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 310, 61, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(340, 10, 194, 22))
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 8, 25), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 340, 61, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 340, 61, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(320, 340, 61, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 310, 61, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 310, 61, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(240, 40, 141, 261))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.Label_33 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_33.setObjectName("Label_33")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_33)
        self.LineEdit_41 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_41.setText("")
        self.LineEdit_41.setObjectName("LineEdit_41")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_41)
        self.Label_34 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_34.setObjectName("Label_34")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_34)
        self.LineEdit_42 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_42.setText("")
        self.LineEdit_42.setObjectName("LineEdit_42")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_42)
        self.Label_35 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_35.setObjectName("Label_35")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_35)
        self.LineEdit_43 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_43.setText("")
        self.LineEdit_43.setObjectName("LineEdit_43")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_43)
        self.Label_36 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_36.setObjectName("Label_36")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_36)
        self.Label_37 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_37.setObjectName("Label_37")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_37)
        self.LineEdit_44 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_44.setObjectName("LineEdit_44")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_44)
        self.Label_38 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_38.setObjectName("Label_38")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_38)
        self.LineEdit_45 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_45.setObjectName("LineEdit_45")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_45)
        self.Label_39 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_39.setObjectName("Label_39")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_39)
        self.LineEdit_46 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_46.setObjectName("LineEdit_46")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_46)
        self.Label_40 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_40.setObjectName("Label_40")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_40)
        self.LineEdit_47 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_47.setObjectName("LineEdit_47")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_47)
        self.lEDLabel_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lEDLabel_5.setObjectName("lEDLabel_5")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel_5)
        self.LineEdit_48 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_48.setObjectName("LineEdit_48")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_48)
        self.bEEPLabel_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.bEEPLabel_5.setObjectName("bEEPLabel_5")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel_5)
        self.LineEdit_49 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_49.setObjectName("LineEdit_49")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_49)
        self.LineEdit_50 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_50.setObjectName("LineEdit_50")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_50)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 340, 61, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(550, 340, 61, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(550, 310, 61, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 310, 61, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(470, 40, 141, 261))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.Label_41 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_41.setObjectName("Label_41")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_41)
        self.LineEdit_51 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_51.setText("")
        self.LineEdit_51.setObjectName("LineEdit_51")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_51)
        self.Label_42 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_42.setObjectName("Label_42")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_42)
        self.LineEdit_52 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_52.setText("")
        self.LineEdit_52.setObjectName("LineEdit_52")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_52)
        self.Label_43 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_43.setObjectName("Label_43")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_43)
        self.LineEdit_53 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_53.setText("")
        self.LineEdit_53.setObjectName("LineEdit_53")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_53)
        self.Label_44 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_44.setObjectName("Label_44")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_44)
        self.Label_45 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_45.setObjectName("Label_45")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_45)
        self.LineEdit_54 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_54.setObjectName("LineEdit_54")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_54)
        self.Label_46 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_46.setObjectName("Label_46")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_46)
        self.LineEdit_55 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_55.setObjectName("LineEdit_55")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_55)
        self.Label_47 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_47.setObjectName("Label_47")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_47)
        self.LineEdit_56 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_56.setObjectName("LineEdit_56")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_56)
        self.Label_48 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_48.setObjectName("Label_48")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_48)
        self.LineEdit_57 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_57.setObjectName("LineEdit_57")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_57)
        self.lEDLabel_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lEDLabel_6.setObjectName("lEDLabel_6")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel_6)
        self.LineEdit_58 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_58.setObjectName("LineEdit_58")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_58)
        self.bEEPLabel_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.bEEPLabel_6.setObjectName("bEEPLabel_6")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel_6)
        self.LineEdit_59 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_59.setObjectName("LineEdit_59")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_59)
        self.LineEdit_60 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_60.setObjectName("LineEdit_60")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_60)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(470, 340, 61, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(780, 340, 61, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(780, 310, 61, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(700, 310, 61, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(700, 40, 141, 261))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.Label_49 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_49.setObjectName("Label_49")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_49)
        self.LineEdit_61 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_61.setText("")
        self.LineEdit_61.setObjectName("LineEdit_61")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_61)
        self.Label_50 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_50.setObjectName("Label_50")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_50)
        self.LineEdit_62 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_62.setText("")
        self.LineEdit_62.setObjectName("LineEdit_62")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_62)
        self.Label_51 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_51.setObjectName("Label_51")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_51)
        self.LineEdit_63 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_63.setText("")
        self.LineEdit_63.setObjectName("LineEdit_63")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_63)
        self.Label_52 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_52.setObjectName("Label_52")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_52)
        self.Label_53 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_53.setObjectName("Label_53")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_53)
        self.LineEdit_64 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_64.setObjectName("LineEdit_64")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_64)
        self.Label_54 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_54.setObjectName("Label_54")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_54)
        self.LineEdit_65 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_65.setObjectName("LineEdit_65")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_65)
        self.Label_55 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_55.setObjectName("Label_55")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_55)
        self.LineEdit_66 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_66.setObjectName("LineEdit_66")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_66)
        self.Label_56 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_56.setObjectName("Label_56")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_56)
        self.LineEdit_67 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_67.setObjectName("LineEdit_67")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_67)
        self.lEDLabel_7 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lEDLabel_7.setObjectName("lEDLabel_7")
        self.formLayout_7.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel_7)
        self.LineEdit_68 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_68.setObjectName("LineEdit_68")
        self.formLayout_7.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_68)
        self.bEEPLabel_7 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.bEEPLabel_7.setObjectName("bEEPLabel_7")
        self.formLayout_7.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel_7)
        self.LineEdit_69 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_69.setObjectName("LineEdit_69")
        self.formLayout_7.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_69)
        self.LineEdit_70 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_70.setObjectName("LineEdit_70")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_70)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(700, 340, 61, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 380, 141, 261))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.Label_57 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_57.setObjectName("Label_57")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_57)
        self.LineEdit_71 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_71.setText("")
        self.LineEdit_71.setObjectName("LineEdit_71")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_71)
        self.Label_58 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_58.setObjectName("Label_58")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_58)
        self.LineEdit_72 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_72.setText("")
        self.LineEdit_72.setObjectName("LineEdit_72")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_72)
        self.Label_59 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_59.setObjectName("Label_59")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_59)
        self.LineEdit_73 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_73.setText("")
        self.LineEdit_73.setObjectName("LineEdit_73")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_73)
        self.Label_60 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_60.setObjectName("Label_60")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_60)
        self.Label_61 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_61.setObjectName("Label_61")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_61)
        self.LineEdit_74 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_74.setObjectName("LineEdit_74")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_74)
        self.Label_62 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_62.setObjectName("Label_62")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_62)
        self.LineEdit_75 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_75.setObjectName("LineEdit_75")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_75)
        self.Label_63 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_63.setObjectName("Label_63")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_63)
        self.LineEdit_76 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_76.setObjectName("LineEdit_76")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_76)
        self.Label_64 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.Label_64.setObjectName("Label_64")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_64)
        self.LineEdit_77 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_77.setObjectName("LineEdit_77")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_77)
        self.lEDLabel_8 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.lEDLabel_8.setObjectName("lEDLabel_8")
        self.formLayout_8.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel_8)
        self.LineEdit_78 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_78.setObjectName("LineEdit_78")
        self.formLayout_8.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_78)
        self.bEEPLabel_8 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.bEEPLabel_8.setObjectName("bEEPLabel_8")
        self.formLayout_8.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel_8)
        self.LineEdit_79 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_79.setObjectName("LineEdit_79")
        self.formLayout_8.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_79)
        self.LineEdit_80 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.LineEdit_80.setObjectName("LineEdit_80")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_80)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(780, 650, 61, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(780, 680, 61, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(550, 680, 61, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(470, 380, 141, 261))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.Label_65 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_65.setObjectName("Label_65")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_65)
        self.LineEdit_81 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_81.setText("")
        self.LineEdit_81.setObjectName("LineEdit_81")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_81)
        self.Label_66 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_66.setObjectName("Label_66")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_66)
        self.LineEdit_82 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_82.setText("")
        self.LineEdit_82.setObjectName("LineEdit_82")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_82)
        self.Label_67 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_67.setObjectName("Label_67")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_67)
        self.LineEdit_83 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_83.setText("")
        self.LineEdit_83.setObjectName("LineEdit_83")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_83)
        self.Label_68 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_68.setObjectName("Label_68")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_68)
        self.Label_69 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_69.setObjectName("Label_69")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_69)
        self.LineEdit_84 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_84.setObjectName("LineEdit_84")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_84)
        self.Label_70 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_70.setObjectName("Label_70")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_70)
        self.LineEdit_85 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_85.setObjectName("LineEdit_85")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_85)
        self.Label_71 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_71.setObjectName("Label_71")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_71)
        self.LineEdit_86 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_86.setObjectName("LineEdit_86")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_86)
        self.Label_72 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_72.setObjectName("Label_72")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_72)
        self.LineEdit_87 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_87.setObjectName("LineEdit_87")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_87)
        self.lEDLabel_9 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.lEDLabel_9.setObjectName("lEDLabel_9")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel_9)
        self.LineEdit_88 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_88.setObjectName("LineEdit_88")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_88)
        self.bEEPLabel_9 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.bEEPLabel_9.setObjectName("bEEPLabel_9")
        self.formLayout_9.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel_9)
        self.LineEdit_89 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_89.setObjectName("LineEdit_89")
        self.formLayout_9.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_89)
        self.LineEdit_90 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_90.setObjectName("LineEdit_90")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_90)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(320, 650, 61, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(240, 680, 61, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 680, 61, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(240, 380, 141, 261))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.Label_73 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_73.setObjectName("Label_73")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_73)
        self.LineEdit_91 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_91.setText("")
        self.LineEdit_91.setObjectName("LineEdit_91")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_91)
        self.Label_74 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_74.setObjectName("Label_74")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_74)
        self.LineEdit_92 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_92.setText("")
        self.LineEdit_92.setObjectName("LineEdit_92")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_92)
        self.Label_75 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_75.setObjectName("Label_75")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_75)
        self.LineEdit_93 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_93.setText("")
        self.LineEdit_93.setObjectName("LineEdit_93")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_93)
        self.Label_76 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_76.setObjectName("Label_76")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_76)
        self.Label_77 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_77.setObjectName("Label_77")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_77)
        self.LineEdit_94 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_94.setObjectName("LineEdit_94")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_94)
        self.Label_78 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_78.setObjectName("Label_78")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_78)
        self.LineEdit_95 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_95.setObjectName("LineEdit_95")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_95)
        self.Label_79 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_79.setObjectName("Label_79")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_79)
        self.LineEdit_96 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_96.setObjectName("LineEdit_96")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_96)
        self.Label_80 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_80.setObjectName("Label_80")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_80)
        self.LineEdit_97 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_97.setObjectName("LineEdit_97")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_97)
        self.lEDLabel_10 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.lEDLabel_10.setObjectName("lEDLabel_10")
        self.formLayout_10.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel_10)
        self.LineEdit_98 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_98.setObjectName("LineEdit_98")
        self.formLayout_10.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_98)
        self.bEEPLabel_10 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.bEEPLabel_10.setObjectName("bEEPLabel_10")
        self.formLayout_10.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel_10)
        self.LineEdit_99 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_99.setObjectName("LineEdit_99")
        self.formLayout_10.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_99)
        self.LineEdit_100 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_100.setObjectName("LineEdit_100")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_100)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(700, 650, 61, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(470, 680, 61, 23))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(470, 650, 61, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(240, 650, 61, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(90, 680, 61, 23))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(320, 680, 61, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(550, 650, 61, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(700, 680, 61, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(700, 380, 141, 261))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_11 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.Label_81 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_81.setObjectName("Label_81")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_81)
        self.LineEdit_101 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_101.setText("")
        self.LineEdit_101.setObjectName("LineEdit_101")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_101)
        self.Label_82 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_82.setObjectName("Label_82")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_82)
        self.LineEdit_102 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_102.setText("")
        self.LineEdit_102.setObjectName("LineEdit_102")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_102)
        self.Label_83 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_83.setObjectName("Label_83")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_83)
        self.LineEdit_103 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_103.setText("")
        self.LineEdit_103.setObjectName("LineEdit_103")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_103)
        self.Label_84 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_84.setObjectName("Label_84")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_84)
        self.Label_85 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_85.setObjectName("Label_85")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_85)
        self.LineEdit_104 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_104.setObjectName("LineEdit_104")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_104)
        self.Label_86 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_86.setObjectName("Label_86")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_86)
        self.LineEdit_105 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_105.setObjectName("LineEdit_105")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_105)
        self.Label_87 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_87.setObjectName("Label_87")
        self.formLayout_11.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_87)
        self.LineEdit_106 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_106.setObjectName("LineEdit_106")
        self.formLayout_11.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_106)
        self.Label_88 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_88.setObjectName("Label_88")
        self.formLayout_11.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_88)
        self.LineEdit_107 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_107.setObjectName("LineEdit_107")
        self.formLayout_11.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit_107)
        self.lEDLabel_11 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.lEDLabel_11.setObjectName("lEDLabel_11")
        self.formLayout_11.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lEDLabel_11)
        self.LineEdit_108 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_108.setObjectName("LineEdit_108")
        self.formLayout_11.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit_108)
        self.bEEPLabel_11 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.bEEPLabel_11.setObjectName("bEEPLabel_11")
        self.formLayout_11.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bEEPLabel_11)
        self.LineEdit_109 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_109.setObjectName("LineEdit_109")
        self.formLayout_11.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit_109)
        self.LineEdit_110 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_110.setObjectName("LineEdit_110")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_110)
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(90, 650, 61, 23))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(10, 650, 61, 23))
        self.pushButton_32.setObjectName("pushButton_32")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(140, 190, 61, 61))
        self.graphicsView.setStyleSheet("border-image: url(:/call/call.png);")
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 23))
        self.menubar.setObjectName("menubar")
        self.menu_IoT = QtWidgets.QMenu(self.menubar)
        self.menu_IoT.setObjectName("menu_IoT")
        self.menuby = QtWidgets.QMenu(self.menubar)
        self.menuby.setObjectName("menuby")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_IoT.menuAction())
        self.menubar.addAction(self.menuby.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label.setText(_translate("MainWindow", "名字"))
        self.Label_2.setText(_translate("MainWindow", "性别"))
        self.Label_3.setText(_translate("MainWindow", "床号"))
        self.Label_8.setText(_translate("MainWindow", "药品"))
        self.Label_9.setText(_translate("MainWindow", "液量"))
        self.Label_10.setText(_translate("MainWindow", "速度"))
        self.Label_11.setText(_translate("MainWindow", "时间"))
        self.Label_12.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel.setText(_translate("MainWindow", "BEEP"))
        self.pushButton.setText(_translate("MainWindow", "LED"))
        self.pushButton_2.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_9.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_10.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_11.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_3.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_4.setText(_translate("MainWindow", "LED"))
        self.Label_33.setText(_translate("MainWindow", "名字"))
        self.Label_34.setText(_translate("MainWindow", "性别"))
        self.Label_35.setText(_translate("MainWindow", "床号"))
        self.Label_36.setText(_translate("MainWindow", "药品"))
        self.Label_37.setText(_translate("MainWindow", "液量"))
        self.Label_38.setText(_translate("MainWindow", "速度"))
        self.Label_39.setText(_translate("MainWindow", "时间"))
        self.Label_40.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel_5.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel_5.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_12.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_13.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_5.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_6.setText(_translate("MainWindow", "LED"))
        self.Label_41.setText(_translate("MainWindow", "名字"))
        self.Label_42.setText(_translate("MainWindow", "性别"))
        self.Label_43.setText(_translate("MainWindow", "床号"))
        self.Label_44.setText(_translate("MainWindow", "药品"))
        self.Label_45.setText(_translate("MainWindow", "液量"))
        self.Label_46.setText(_translate("MainWindow", "速度"))
        self.Label_47.setText(_translate("MainWindow", "时间"))
        self.Label_48.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel_6.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel_6.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_14.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_15.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_7.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_8.setText(_translate("MainWindow", "LED"))
        self.Label_49.setText(_translate("MainWindow", "名字"))
        self.Label_50.setText(_translate("MainWindow", "性别"))
        self.Label_51.setText(_translate("MainWindow", "床号"))
        self.Label_52.setText(_translate("MainWindow", "药品"))
        self.Label_53.setText(_translate("MainWindow", "液量"))
        self.Label_54.setText(_translate("MainWindow", "速度"))
        self.Label_55.setText(_translate("MainWindow", "时间"))
        self.Label_56.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel_7.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel_7.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_16.setText(_translate("MainWindow", "清除信息"))
        self.Label_57.setText(_translate("MainWindow", "名字"))
        self.Label_58.setText(_translate("MainWindow", "性别"))
        self.Label_59.setText(_translate("MainWindow", "床号"))
        self.Label_60.setText(_translate("MainWindow", "药品"))
        self.Label_61.setText(_translate("MainWindow", "液量"))
        self.Label_62.setText(_translate("MainWindow", "速度"))
        self.Label_63.setText(_translate("MainWindow", "时间"))
        self.Label_64.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel_8.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel_8.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_17.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_18.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_19.setText(_translate("MainWindow", "更新信息"))
        self.Label_65.setText(_translate("MainWindow", "名字"))
        self.Label_66.setText(_translate("MainWindow", "性别"))
        self.Label_67.setText(_translate("MainWindow", "床号"))
        self.Label_68.setText(_translate("MainWindow", "药品"))
        self.Label_69.setText(_translate("MainWindow", "液量"))
        self.Label_70.setText(_translate("MainWindow", "速度"))
        self.Label_71.setText(_translate("MainWindow", "时间"))
        self.Label_72.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel_9.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel_9.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_20.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_21.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_22.setText(_translate("MainWindow", "清除信息"))
        self.Label_73.setText(_translate("MainWindow", "名字"))
        self.Label_74.setText(_translate("MainWindow", "性别"))
        self.Label_75.setText(_translate("MainWindow", "床号"))
        self.Label_76.setText(_translate("MainWindow", "药品"))
        self.Label_77.setText(_translate("MainWindow", "液量"))
        self.Label_78.setText(_translate("MainWindow", "速度"))
        self.Label_79.setText(_translate("MainWindow", "时间"))
        self.Label_80.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel_10.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel_10.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_23.setText(_translate("MainWindow", "LED"))
        self.pushButton_24.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_25.setText(_translate("MainWindow", "LED"))
        self.pushButton_26.setText(_translate("MainWindow", "LED"))
        self.pushButton_27.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_28.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_29.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_30.setText(_translate("MainWindow", "清除信息"))
        self.Label_81.setText(_translate("MainWindow", "名字"))
        self.Label_82.setText(_translate("MainWindow", "性别"))
        self.Label_83.setText(_translate("MainWindow", "床号"))
        self.Label_84.setText(_translate("MainWindow", "药品"))
        self.Label_85.setText(_translate("MainWindow", "液量"))
        self.Label_86.setText(_translate("MainWindow", "速度"))
        self.Label_87.setText(_translate("MainWindow", "时间"))
        self.Label_88.setText(_translate("MainWindow", "呼叫"))
        self.lEDLabel_11.setText(_translate("MainWindow", "LED"))
        self.bEEPLabel_11.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_31.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_32.setText(_translate("MainWindow", "LED"))
        self.menu_IoT.setTitle(_translate("MainWindow", "【IoT迷你赛】智慧医疗之输液监控终端"))
        self.menuby.setTitle(_translate("MainWindow", "by杰杰"))

import call_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

