# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinPyQt5.9-32bit-3.5.3.1\eric_work\wit\wit.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 623)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 60, 141, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.Label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_4)
        self.Label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.LineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_5)
        self.Label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_6.setObjectName("Label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.LineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_6)
        self.Label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_7.setObjectName("Label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.LineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_7)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 250, 61, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 250, 61, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 250, 61, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(640, 250, 61, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(440, 330, 141, 181))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.Label_50 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_50.setObjectName("Label_50")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_50)
        self.LineEdit_50 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_50.setObjectName("LineEdit_50")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_50)
        self.Label_51 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_51.setObjectName("Label_51")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_51)
        self.LineEdit_51 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_51.setObjectName("LineEdit_51")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_51)
        self.Label_52 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_52.setObjectName("Label_52")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_52)
        self.LineEdit_52 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_52.setObjectName("LineEdit_52")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_52)
        self.Label_53 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_53.setObjectName("Label_53")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_53)
        self.LineEdit_53 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_53.setObjectName("LineEdit_53")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_53)
        self.Label_54 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_54.setObjectName("Label_54")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_54)
        self.LineEdit_54 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_54.setObjectName("LineEdit_54")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_54)
        self.Label_55 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_55.setObjectName("Label_55")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_55)
        self.LineEdit_55 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_55.setObjectName("LineEdit_55")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_55)
        self.Label_56 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.Label_56.setObjectName("Label_56")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_56)
        self.LineEdit_56 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.LineEdit_56.setObjectName("LineEdit_56")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_56)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(640, 330, 141, 181))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.Label_64 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_64.setObjectName("Label_64")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_64)
        self.LineEdit_64 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_64.setObjectName("LineEdit_64")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_64)
        self.Label_65 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_65.setObjectName("Label_65")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_65)
        self.LineEdit_65 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_65.setObjectName("LineEdit_65")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_65)
        self.Label_66 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_66.setObjectName("Label_66")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_66)
        self.LineEdit_66 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_66.setObjectName("LineEdit_66")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_66)
        self.Label_67 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_67.setObjectName("Label_67")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_67)
        self.LineEdit_67 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_67.setObjectName("LineEdit_67")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_67)
        self.Label_68 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_68.setObjectName("Label_68")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_68)
        self.LineEdit_68 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_68.setObjectName("LineEdit_68")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_68)
        self.Label_69 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_69.setObjectName("Label_69")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_69)
        self.LineEdit_69 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_69.setObjectName("LineEdit_69")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_69)
        self.Label_70 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.Label_70.setObjectName("Label_70")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_70)
        self.LineEdit_70 = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.LineEdit_70.setObjectName("LineEdit_70")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_70)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 250, 61, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(720, 520, 61, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(300, 520, 61, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(520, 520, 61, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(220, 520, 61, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(220, 60, 141, 181))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.LineEdit_8 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_8)
        self.Label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_9.setObjectName("Label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.LineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_9.setObjectName("LineEdit_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_9)
        self.Label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_10.setObjectName("Label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.LineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_10.setObjectName("LineEdit_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_10)
        self.Label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_11.setObjectName("Label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.LineEdit_11 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_11.setObjectName("LineEdit_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_11)
        self.Label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_12.setObjectName("Label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.LineEdit_12 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_12.setObjectName("LineEdit_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_12)
        self.Label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_13.setObjectName("Label_13")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.LineEdit_13 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_13.setObjectName("LineEdit_13")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_13)
        self.Label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_14.setObjectName("Label_14")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_14)
        self.LineEdit_14 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LineEdit_14.setObjectName("LineEdit_14")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_14)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(640, 520, 61, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(640, 60, 141, 181))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.Label_22 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_22.setObjectName("Label_22")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_22)
        self.LineEdit_22 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_22.setObjectName("LineEdit_22")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_22)
        self.Label_23 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_23.setObjectName("Label_23")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_23)
        self.LineEdit_23 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_23.setObjectName("LineEdit_23")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_23)
        self.Label_24 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_24.setObjectName("Label_24")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_24)
        self.LineEdit_24 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_24.setObjectName("LineEdit_24")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_24)
        self.Label_25 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_25.setObjectName("Label_25")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_25)
        self.LineEdit_25 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_25.setObjectName("LineEdit_25")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_25)
        self.Label_26 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_26.setObjectName("Label_26")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_26)
        self.LineEdit_26 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_26.setObjectName("LineEdit_26")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_26)
        self.Label_27 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_27.setObjectName("Label_27")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_27)
        self.LineEdit_27 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_27.setObjectName("LineEdit_27")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_27)
        self.Label_28 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.Label_28.setObjectName("Label_28")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_28)
        self.LineEdit_28 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LineEdit_28.setObjectName("LineEdit_28")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_28)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(220, 330, 141, 181))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.Label_43 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_43.setObjectName("Label_43")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_43)
        self.LineEdit_43 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_43.setObjectName("LineEdit_43")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_43)
        self.Label_44 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_44.setObjectName("Label_44")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_44)
        self.LineEdit_44 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_44.setObjectName("LineEdit_44")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_44)
        self.Label_45 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_45.setObjectName("Label_45")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_45)
        self.LineEdit_45 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_45.setObjectName("LineEdit_45")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_45)
        self.Label_46 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_46.setObjectName("Label_46")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_46)
        self.LineEdit_46 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_46.setObjectName("LineEdit_46")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_46)
        self.Label_47 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_47.setObjectName("Label_47")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_47)
        self.LineEdit_47 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_47.setObjectName("LineEdit_47")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_47)
        self.Label_48 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_48.setObjectName("Label_48")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_48)
        self.LineEdit_48 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_48.setObjectName("LineEdit_48")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_48)
        self.Label_49 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.Label_49.setObjectName("Label_49")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_49)
        self.LineEdit_49 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.LineEdit_49.setObjectName("LineEdit_49")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_49)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(720, 250, 61, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 250, 61, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(280, 10, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(440, 60, 141, 181))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_15.setObjectName("Label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_15)
        self.LineEdit_15 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_15.setObjectName("LineEdit_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_15)
        self.Label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_16.setObjectName("Label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_16)
        self.LineEdit_16 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_16.setObjectName("LineEdit_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_16)
        self.Label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_17.setObjectName("Label_17")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_17)
        self.LineEdit_17 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_17.setObjectName("LineEdit_17")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_17)
        self.Label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_18.setObjectName("Label_18")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_18)
        self.LineEdit_18 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_18.setObjectName("LineEdit_18")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_18)
        self.Label_19 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_19.setObjectName("Label_19")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_19)
        self.LineEdit_19 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_19.setObjectName("LineEdit_19")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_19)
        self.Label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_20.setObjectName("Label_20")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_20)
        self.LineEdit_20 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_20.setObjectName("LineEdit_20")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_20)
        self.Label_21 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_21.setObjectName("Label_21")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_21)
        self.LineEdit_21 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_21.setObjectName("LineEdit_21")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_21)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(440, 520, 61, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 250, 61, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(100, 520, 61, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 520, 61, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(20, 330, 141, 181))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.Label_57 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.Label_57.setObjectName("Label_57")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_57)
        self.LineEdit_57 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.LineEdit_57.setObjectName("LineEdit_57")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_57)
        self.Label_58 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.Label_58.setObjectName("Label_58")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_58)
        self.LineEdit_58 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.LineEdit_58.setObjectName("LineEdit_58")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_58)
        self.Label_59 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.Label_59.setObjectName("Label_59")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_59)
        self.LineEdit_59 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.LineEdit_59.setObjectName("LineEdit_59")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_59)
        self.Label_60 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.Label_60.setObjectName("Label_60")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_60)
        self.LineEdit_60 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.LineEdit_60.setObjectName("LineEdit_60")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_60)
        self.Label_61 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.Label_61.setObjectName("Label_61")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_61)
        self.LineEdit_61 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.LineEdit_61.setObjectName("LineEdit_61")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_61)
        self.Label_62 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.Label_62.setObjectName("Label_62")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_62)
        self.LineEdit_62 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.LineEdit_62.setObjectName("LineEdit_62")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_62)
        self.Label_63 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.Label_63.setObjectName("Label_63")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_63)
        self.LineEdit_63 = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.LineEdit_63.setObjectName("LineEdit_63")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_63)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 280, 61, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 280, 61, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(300, 280, 61, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(220, 280, 61, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(520, 280, 61, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(440, 280, 61, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(720, 280, 61, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(640, 280, 61, 23))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(720, 550, 61, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(100, 550, 61, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(220, 550, 61, 23))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(440, 550, 61, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(300, 550, 61, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(20, 550, 61, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(640, 550, 61, 23))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(520, 550, 61, 23))
        self.pushButton_32.setObjectName("pushButton_32")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 23))
        self.menubar.setObjectName("menubar")
        self.menu_IoT = QtWidgets.QMenu(self.menubar)
        self.menu_IoT.setObjectName("menu_IoT")
        self.menuby = QtWidgets.QMenu(self.menubar)
        self.menuby.setObjectName("menuby")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_IoT.menuAction())
        self.menubar.addAction(self.menuby.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label.setText(_translate("MainWindow", "名字"))
        self.LineEdit.setText(_translate("MainWindow", "name"))
        self.Label_2.setText(_translate("MainWindow", "性别"))
        self.LineEdit_2.setText(_translate("MainWindow", "man"))
        self.Label_3.setText(_translate("MainWindow", "床号"))
        self.LineEdit_3.setText(_translate("MainWindow", "66"))
        self.Label_4.setText(_translate("MainWindow", "液量"))
        self.LineEdit_4.setText(_translate("MainWindow", "97"))
        self.Label_5.setText(_translate("MainWindow", "速度"))
        self.LineEdit_5.setText(_translate("MainWindow", "1"))
        self.Label_6.setText(_translate("MainWindow", "时间"))
        self.LineEdit_6.setText(_translate("MainWindow", "1024"))
        self.Label_7.setText(_translate("MainWindow", "呼叫"))
        self.LineEdit_7.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "LED"))
        self.pushButton_2.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_6.setText(_translate("MainWindow", "LED"))
        self.pushButton_8.setText(_translate("MainWindow", "LED"))
        self.Label_50.setText(_translate("MainWindow", "名字"))
        self.Label_51.setText(_translate("MainWindow", "性别"))
        self.Label_52.setText(_translate("MainWindow", "床号"))
        self.Label_53.setText(_translate("MainWindow", "液量"))
        self.Label_54.setText(_translate("MainWindow", "速度"))
        self.Label_55.setText(_translate("MainWindow", "时间"))
        self.Label_56.setText(_translate("MainWindow", "呼叫"))
        self.Label_64.setText(_translate("MainWindow", "名字"))
        self.Label_65.setText(_translate("MainWindow", "性别"))
        self.Label_66.setText(_translate("MainWindow", "床号"))
        self.Label_67.setText(_translate("MainWindow", "液量"))
        self.Label_68.setText(_translate("MainWindow", "速度"))
        self.Label_69.setText(_translate("MainWindow", "时间"))
        self.Label_70.setText(_translate("MainWindow", "呼叫"))
        self.pushButton_5.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_15.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_11.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_13.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_12.setText(_translate("MainWindow", "LED"))
        self.Label_8.setText(_translate("MainWindow", "名字"))
        self.Label_9.setText(_translate("MainWindow", "性别"))
        self.Label_10.setText(_translate("MainWindow", "床号"))
        self.Label_11.setText(_translate("MainWindow", "液量"))
        self.Label_12.setText(_translate("MainWindow", "速度"))
        self.Label_13.setText(_translate("MainWindow", "时间"))
        self.Label_14.setText(_translate("MainWindow", "呼叫"))
        self.pushButton_16.setText(_translate("MainWindow", "LED"))
        self.Label_22.setText(_translate("MainWindow", "名字"))
        self.Label_23.setText(_translate("MainWindow", "性别"))
        self.Label_24.setText(_translate("MainWindow", "床号"))
        self.Label_25.setText(_translate("MainWindow", "液量"))
        self.Label_26.setText(_translate("MainWindow", "速度"))
        self.Label_27.setText(_translate("MainWindow", "时间"))
        self.Label_28.setText(_translate("MainWindow", "呼叫"))
        self.Label_43.setText(_translate("MainWindow", "名字"))
        self.Label_44.setText(_translate("MainWindow", "性别"))
        self.Label_45.setText(_translate("MainWindow", "床号"))
        self.Label_46.setText(_translate("MainWindow", "液量"))
        self.Label_47.setText(_translate("MainWindow", "速度"))
        self.Label_48.setText(_translate("MainWindow", "时间"))
        self.Label_49.setText(_translate("MainWindow", "呼叫"))
        self.pushButton_7.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_4.setText(_translate("MainWindow", "LED"))
        self.Label_15.setText(_translate("MainWindow", "名字"))
        self.Label_16.setText(_translate("MainWindow", "性别"))
        self.Label_17.setText(_translate("MainWindow", "床号"))
        self.Label_18.setText(_translate("MainWindow", "液量"))
        self.Label_19.setText(_translate("MainWindow", "速度"))
        self.Label_20.setText(_translate("MainWindow", "时间"))
        self.Label_21.setText(_translate("MainWindow", "呼叫"))
        self.pushButton_14.setText(_translate("MainWindow", "LED"))
        self.pushButton_3.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_17.setText(_translate("MainWindow", "BEEP"))
        self.pushButton_18.setText(_translate("MainWindow", "LED"))
        self.Label_57.setText(_translate("MainWindow", "名字"))
        self.Label_58.setText(_translate("MainWindow", "性别"))
        self.Label_59.setText(_translate("MainWindow", "床号"))
        self.Label_60.setText(_translate("MainWindow", "液量"))
        self.Label_61.setText(_translate("MainWindow", "速度"))
        self.Label_62.setText(_translate("MainWindow", "时间"))
        self.Label_63.setText(_translate("MainWindow", "呼叫"))
        self.pushButton_9.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_10.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_19.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_20.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_21.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_22.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_23.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_24.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_25.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_26.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_27.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_28.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_29.setText(_translate("MainWindow", "更新信息"))
        self.pushButton_30.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_31.setText(_translate("MainWindow", "清除信息"))
        self.pushButton_32.setText(_translate("MainWindow", "更新信息"))
        self.menu_IoT.setTitle(_translate("MainWindow", "【IoT迷你赛】智慧医疗之输液监控终端"))
        self.menuby.setTitle(_translate("MainWindow", "by杰杰"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

